### ISSUE TITLE
Add device wise mode

### ISSUE THREAD

**Issue by devajayarora** [apnsngr/bulma-popover#6]
Currently, we can not use different position modifiers as per the viewport (device).

Scenario, If I want to use `.is-popover-bottom` on desktop and above and `.is-popover-right` to mobile and tablet devices.
As bulma navbar in mobile devices opens in the left side and does not give any space to view.

**Comment by apnsngr** [comment]
Hello! Thanks so much for your feature request! I will try to add this soon (aiming for Friday or Saturday, but it might be next week).

I am planning to make it similar to the responsive columns in Bulma. So for your example above it would be something like `class=“popover is-popover-right is-popover-bottom-desktop”`. Does that sound good to you?

**Comment by devajayarora** [comment]
Thanks for accepting the request.
It should be like `class="popover is-popover-right-mobile is-popover-bottom-desktop"`
`is-popover-{position}-{device}`

**Comment by apnsngr** [comment]
I published 1.1.0-beta.0 which includes responsive positioning classes. The classes follow [Bulma's responsive breakpoints](https://bulma.io/documentation/overview/responsiveness/#breakpoints). This means that you will need to use `class=“popover is-popover-right is-popover-bottom-desktop”` or `class=“popover is-popover-right-touch is-popover-bottom-desktop”` to get what you originally asked. Using `class="popover is-popover-right-mobile is-popover-bottom-desktop"` would result in a top popover for tablet devices, since Bulma's mobile breakpoint is mobile only (i.e. does not include widths larger than the tablet minimum).

Could you please install the beta version and test it out to double check it will work for you?

**Comment by apnsngr** [comment]
This feature has now been published as part of the 1.1.0 release.
